services:
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync+restart
          path: ./app/
          target: /app
        - action: rebuild
          path: requirements.txt
